source 'http://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'

gem 'presenting', :path => File.dirname(__FILE__) + '/../../'
gem 'will_paginate', '~>3.0.4'

group :test do
  gem 'mocha', :require => nil
end
