source 'http://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'presenting', :path => File.dirname(__FILE__) + '/../../'
gem 'will_paginate', '~>3.0.4'
gem 'actionpack-page_caching'

group :test do
  gem 'mocha', :require => nil
end